services:
  - type: web
    name: management-system
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CONNECTION_STRING
        sync: false
      - key: JWT_SECRET
        sync: false
